import { Automation, ActionType, MemoryType, TaskStatus } from '@prisma/client';
import { TaskService } from '../task.service';
import { MemoryService } from '../memory.service';
import { BadRequestError } from '../../utils/errors';

export class ActionRunnerService {
  private taskService: TaskService;
  private memoryService: MemoryService;

  constructor(
    taskService: TaskService = new TaskService(),
    memoryService: MemoryService = new MemoryService(),
  ) {
    this.taskService = taskService;
    this.memoryService = memoryService;
  }

  async runAction(
    automation: Automation,
    userId: string,
    input?: Record<string, unknown>,
  ): Promise<Record<string, unknown>> {
    const metadata = (automation.metadata as Record<string, unknown>) ?? {};
    const actionPayload = { ...metadata, ...(input || {}) };

    switch (automation.actionType) {
      case ActionType.CREATE_TASK: {
        const title =
          typeof actionPayload.title === 'string'
            ? actionPayload.title
            : `Automated Task: ${automation.name}`;
        const description =
          typeof actionPayload.description === 'string'
            ? actionPayload.description
            : automation.description || undefined;

        const task = await this.taskService.createTask(userId, automation.projectId, {
          title,
          description,
        });
        return { action: 'CREATE_TASK', taskId: task.id, title: task.title };
      }

      case ActionType.UPDATE_TASK_STATUS: {
        const taskId = typeof actionPayload.taskId === 'string' ? actionPayload.taskId : undefined;
        const status = actionPayload.status as TaskStatus | undefined;
        if (!taskId || !status) {
          throw new BadRequestError('UPDATE_TASK_STATUS requires taskId and status');
        }
        const updatedTask = await this.taskService.updateTask(userId, taskId, { status });
        return { action: 'UPDATE_TASK_STATUS', taskId: updatedTask.id, status: updatedTask.status };
      }

      case ActionType.CREATE_MEMORY: {
        const title =
          typeof actionPayload.title === 'string'
            ? actionPayload.title
            : `Automated Memory: ${automation.name}`;
        const content =
          typeof actionPayload.content === 'string'
            ? actionPayload.content
            : `Generated by automation ${automation.id}`;
        const type = (actionPayload.type as MemoryType) || MemoryType.SYSTEM;
        const importance =
          typeof actionPayload.importance === 'number' ? actionPayload.importance : 5;
        const tags = Array.isArray(actionPayload.tags)
          ? (actionPayload.tags as string[])
          : ['automation'];

        const memory = await this.memoryService.createMemory(userId, automation.projectId, {
          title,
          content,
          type,
          importance,
          tags,
        });

        return { action: 'CREATE_MEMORY', memoryId: memory.id, title: memory.title };
      }

      case ActionType.SEND_INTERNAL_NOTIFICATION: {
        const message =
          typeof actionPayload.message === 'string'
            ? actionPayload.message
            : `Automation ${automation.name} executed successfully.`;
        return {
          action: 'SEND_INTERNAL_NOTIFICATION',
          notified: true,
          message,
          timestamp: new Date().toISOString(),
        };
      }

      case ActionType.LOG_EVENT: {
        return {
          action: 'LOG_EVENT',
          logged: true,
          automationId: automation.id,
          automationName: automation.name,
          timestamp: new Date().toISOString(),
        };
      }

      default:
        throw new BadRequestError(`Unsupported action type: ${automation.actionType}`);
    }
  }
}
